// <auto-generated />
using System;
using HealthStore.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthStore.API.Migrations
{
    [DbContext(typeof(HSDbContext))]
    [Migration("20250630175607_Seeding Data for Patient")]
    partial class SeedingDataforPatient
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("HealthStore.API.Models.Domain.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientDoc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientName")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("INTEGER");

                    b.Property<float>("weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f5d33a7-9ac7-4fc1-84a3-21e1c1829f7e"),
                            PatientDoc = "Mr. String",
                            PatientName = "GHJ",
                            PhoneNumber = 1234567890,
                            weight = 66.6f
                        });
                });

            modelBuilder.Entity("HealthStore.API.Models.Domain.Vitals", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BeatsPerMinute")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BloodPressure")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatDoc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SPO2")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SugarLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Temperature")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vitals");
                });
#pragma warning restore 612, 618
        }
    }
}
